

# VERBOSITY
/run/verbose 1
/event/verbose 0
/tracking/verbose 0
/process/em/verbose 0
## Making sure electroluminescence is turned on


## Nexus Physics List
/PhysicsList/Nexus/clustering           true
/PhysicsList/Nexus/drift                true
/PhysicsList/Nexus/electroluminescence  true

## Get GeometryInfo
/nexus/RegisterMacro macros/CRAB/Camera/Detector_config.mac


#/Generator/SingleParticle/region FIELDCAGE

/Generator/SingleParticle/region OUTER_SURFACE

/Generator/SingleParticle/particle opticalphoton
/Generator/SingleParticle/min_energy 7.20 eV
/Generator/SingleParticle/max_energy 7.20 eV

#/Generator/SingleParticle/particle alpha
#/Generator/SingleParticle/min_energy 0.5 keV
#/Generator/SingleParticle/max_energy 0.5 keV

#/Generator/SingleParticle/min_costheta 1
#/Generator/SingleParticle/max_costheta 1
#/Generator/SingleParticle/min_phi 0
#/Generator/SingleParticle/max_phi 0


### Isotropic Photon  Emmission
/Generator/SingleParticle/min_costheta -1
/Generator/SingleParticle/max_costheta 1
/Generator/SingleParticle/min_phi -3.14
/Generator/SingleParticle/max_phi 3.14

/Actions/CRABAnalysisSteppingAction/FileSave true

#### Attention! ---> if CRABOpticalTrackingAction is selected , please pay attention to this line. it allows you to select what particles to save to file and visualize.
## Particle Type
## optical saves and tracks only photons
## ie saves and tracks only ionization electrons
## all saves and tracks both ionization and optical

# Comment this out if you do not want to use this TrackingAction
/TrackingAction/CRABOpticalTrackingAction/Particle_Type optical

# PERSISTENCY
/nexus/persistency/eventType background
/nexus/persistency/outputFile /media/ilker/Ilker/CRAB/Simulation/test
#/run/printProgress 100
