## ----------------------------------------------------------------------------
## nexus | DEMOPP_fullKr.init.mac
##
## Initialization macro to simulate Kr-83 decays in the DEMO++ geometry
## with generation and transportation of optical photons.
##
## The NEXT Collaboration
## ----------------------------------------------------------------------------


/PhysicsList/RegisterPhysics G4EmStandardPhysics_option4
/PhysicsList/RegisterPhysics G4DecayPhysics
/PhysicsList/RegisterPhysics G4RadioactiveDecayPhysics
/PhysicsList/RegisterPhysics G4OpticalPhysics
/PhysicsList/RegisterPhysics NexusPhysics
/PhysicsList/RegisterPhysics G4StepLimiterPhysics


/nexus/RegisterGeometry CRAB_Detector

/nexus/RegisterGenerator SingleParticleGenerator

/nexus/RegisterPersistencyManager PersistencyManager

/nexus/RegisterTrackingAction CRABOpticalTrackingAction
/nexus/RegisterEventAction DefaultEventAction
/nexus/RegisterRunAction DefaultRunAction
/nexus/RegisterSteppingAction CRABAnalysisSteppingAction


/nexus/RegisterMacro macros/CRAB/Camera/CRAB_Detector_Test_config.mac
