
##### VERBOSITY #####
/run/verbose 0
/event/verbose 0
/tracking/verbose 0

/process/em/verbose 0

/Geometry/XeSphere/LXe false
/Geometry/XeSphere/pressure 15 bar
/Geometry/XeSphere/radius 10. m

# use C++ translation of DECAY0
/Generator/Decay0Interface/inputFile none
# for 0 neutrino  bb to Barium Ground state.
/Generator/Decay0Interface/Xe136DecayMode 1
# for 2 neutrino  bb to Barium Ground state.
#/Generator/Decay0Interface/Xe136DecayMode 4
#/Generator/Decay0Interface/EnergyThreshold 0.5
#
/Generator/Decay0Interface/Ba136FinalState 0

/Generator/Decay0Interface/region CENTER

### Physics
/PhysicsList/Nexus/clustering          true
/PhysicsList/Nexus/drift               false
/PhysicsList/Nexus/electroluminescence false
/PhysicsList/Nexus/fastsim false


/nexus/persistency/output_file Xe136_test_15bar

