## ----------------------------------------------------------------------------
## nexus | NEXT100.config.mac
##
## Configuration macro to simulate Bi-214 radioactive decays from thethe
## copper plate of the tracking plane in the NEXT-100 detector.
##
## The NEXT Collaboration
## ----------------------------------------------------------------------------

##### VERBOSITY #####
/run/verbose 0
/event/verbose 0
/tracking/verbose 0

/process/em/verbose 0

##### GEOMETRY #####
#/Geometry/Next100/elfield false
#/Geometry/Next100/max_step_size 1. mm
/Geometry/CRAB0/useCAD false

# Garfield
/Geometry/CRAB0/DetChamberD 16.4 cm
/Geometry/CRAB0/DetChamberL 43.18 cm
/Geometry/CRAB0/DetActiveD 8.6 cm
/Geometry/CRAB0/DetActiveL 21.26 cm
/Geometry/CRAB0/GasPressure 8 bar
/Geometry/CRAB0/fieldDrift 438.0
/Geometry/CRAB0/fieldEL 7857.14
/Geometry/CRAB0/GasFile /home/argon/Projects/Ilker/CRAB_Diffusion/CRAB/GasFiles/Xe100_8.09bar.gas
# Normaly 25510/MeV
/Geometry/CRAB0/ScintYield 25510 #25510
## for 8 bar Xenon
/Geometry/CRAB0/EL_Diffusion  2.01 0.45 0.19
/Geometry/CRAB0/FieldCage_Diffusion 0.99 1.13 0.38
# Comsol Related info
/Geometry/CRAB0/ComsolPath /home/argon/Projects/Ilker/CRAB_COMSOL/With_Needles/13.5k_8k_7k/8bar/
/Geometry/CRAB0/MeshFile CRAB_Mesh.mphtxt
/Geometry/CRAB0/Data CRAB_Data.txt
/Geometry/CRAB0/Materials CRABMaterialProperties.txt

##### GENERATOR #####
#/Generator/SingleParticle/particle opticalphoton
#/Generator/SingleParticle/min_energy 7.2 eV
/Generator/SingleParticle/particle alpha
/Generator/SingleParticle/max_energy 5.4 MeV
/Generator/SingleParticle/min_energy 5.4 MeV
#/Generator/SingleParticle/particle e-
#/Generator/SingleParticle/min_energy 1 MeV

/Generator/SingleParticle/region CENTER


#/Generator/SingleParticle/region NEEDLE
/Geometry/CRAB0/specific_vertex 0 0 0 mm

##### ACTIONS #####
#/Actions/DefaultEventAction/min_energy 0.6 keV
#/Actions/DefaultEventAction/max_energy 2.55 MeV
## For Debugging (Opticks)
/Actions/OpticksSaveAllSteppingAction/select_particle opticalphoton
#/Actions/OpticksSaveAllSteppingAction/select_volume   ACTIVE   #    full match
#/Actions/OpticksSaveAllSteppingAction/select_volume   EL_GAP      # partial match
/Actions/OpticksSaveAllSteppingAction/select_volume   PMT_TUBE0      # partial match
/Actions/OpticksSaveAllSteppingAction/select_volume   PMT_TUBE1      # partial match
/Actions/OpticksSaveAllSteppingAction/select_volume   Lens      # partial match
/Actions/OpticksSaveAllSteppingAction/select_volume   MgF2_WINDOW      # partial match
/Actions/OpticksSaveAllSteppingAction/select_volume   camWindow      # partial match
/Actions/OpticksSaveAllSteppingAction/select_volume   PMTWindow      # partial match
/Actions/OpticksSaveAllSteppingAction/select_volume   LAB      # partial match
#/Actions/OpticksSaveAllSteppingAction/kill_after_selection False


##### PHYSICS #####
## No full simulation
/PhysicsList/Nexus/clustering          false
/PhysicsList/Nexus/drift               false
/PhysicsList/Nexus/electroluminescence false
/PhysicsList/Nexus/fastsim false



##### PERSISTENCY #####
/nexus/persistency/output_file output/Opticks_Hit_Comparison/S1s_debug
## eventType options: bb0nu, bb2nu, background
/nexus/persistency/event_type data
