## ----------------------------------------------------------------------------
## nexus | NEXT100.config.mac
##
## Configuration macro to simulate Bi-214 radioactive decays from thethe
## copper plate of the tracking plane in the NEXT-100 detector.
##
## The NEXT Collaboration
## ----------------------------------------------------------------------------

##### VERBOSITY #####
/run/verbose 0
/event/verbose 0
/tracking/verbose 0

/process/em/verbose 0

##### GEOMETRY #####
#/Geometry/Next100/elfield false
#/Geometry/Next100/max_step_size 1. mm

#seed
/nexus/random_seed 2


/Geometry/CRAB0/DetChamberD 16.4 cm
/Geometry/CRAB0/DetChamberL 43.18 cm
/Geometry/CRAB0/DetActiveD 8.6 cm
/Geometry/CRAB0/DetActiveL 21.26 cm

### Pressure ###
#/Geometry/CRAB0/GasPressure 8 bar
/Geometry/CRAB0/GasPressure 10 bar

### Garfield ###
/Geometry/CRAB0/fieldDrift 438.0
/Geometry/CRAB0/fieldEL 7857.14
/Geometry/CRAB0/SimpleField true
/Geometry/CRAB0/GasFile /home/argon/Projects/Ilker/CRAB_Diffusion/CRAB/GasFiles/Xe100_8.09bar.gas

# This is for shifting detectors into CRAB
/Geometry/CRAB0/ShiftDetectors false

## Turns of the reflections
/Geometry/CRAB0/SteelReflect true
/Geometry/CRAB0/useSimpleGeometry false
# Normaly 25510/MeV
/Geometry/CRAB0/ScintYield 25510 #25510
/Geometry/CRAB0/ELYield 0 #925
#### Using Uniform Electrical Fields Without Garfield ####
## for 8 bar Xenon
#/Geometry/CRAB0/EL_Diffusion  2.01 0.45 0.19
#/Geometry/CRAB0/FieldCage_Diffusion 0.99 1.13 0.38
## for 10 bar Xenon
/Geometry/CRAB0/EL_Diffusion  4.6 0.24 0.17
/Geometry/CRAB0/FieldCage_Diffusion 0.90 0.92 0.36


##### GENERATOR #####
#/Generator/SPModified/particle opticalphoton
#/Generator/SPModified/min_energy 7.2 eV
/Generator/SPModified/particle alpha
/Generator/SPModified/max_energy 5.3 MeV
/Generator/SPModified/min_energy 5.3 MeV
#/Generator/SPModified/particle e-
#/Generator/SPModified/min_energy 1 MeV

/Generator/SPModified/Mode regular

/Generator/SPModified/region AD_HOC


#/Generator/SPModified/region NEEDLE
/Geometry/CRAB0/specific_vertex -10 10 -10 mm
#/Geometry/CRAB0/specific_vertex 0 0 0 mm

##### ACTIONS #####
#/Actions/DefaultEventAction/min_energy 0.6 keV
#/Actions/DefaultEventAction/max_energy 2.55 MeV


##### PHYSICS #####
## No full simulation
/PhysicsList/Nexus/clustering          true
/PhysicsList/Nexus/drift               true
/PhysicsList/Nexus/electroluminescence true
/PhysicsList/Nexus/fastsim false



##### PERSISTENCY #####
/nexus/persistency/output_file t #OpticksOnly_ReflectionsOFF_CAM_GAS_May30

## eventType options: bb0nu, bb2nu, background
/nexus/persistency/event_type run
